name: macos-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: run build
      run: |
        cmake . -DCMAKE_CXX_COMPILER=g++-11
        make
        cmake . -DCMAKE_CXX_COMPILER=g++-11 -DENABLE_STYLES=ON
        make
