
name: pvs-studio

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  PVS-Studio:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Installing vcpkg
        run: |
          cd ..
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh

      - name: Installing PVS-Studio
        env:
          # The Secret variable setup in GitHub must be in format: "name_or_email key", on a single line
          PVS_STUDIO_LICENSE: ${{ secrets.PVS_STUDIO_LICENSE }}
        run: |
          wget -q -O - https://files.pvs-studio.com/etc/pubkey.txt \
            | sudo apt-key add -
          sudo wget -O /etc/apt/sources.list.d/viva64.list \
            https://files.pvs-studio.com/etc/viva64.list
          sudo apt update
          sudo apt install pvs-studio
          pvs-studio-analyzer credentials ${{ secrets.PVS_STUDIO_CREDENTIALS }}   

      - name: Downloading dependencies
        run: |
          cd ${{ github.workspace }}
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=On -B -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/../vcpkg/scripts/buildsystems/vcpkg.cmake build .
          cmake --build build -j

      - name: Running PVS-Studio
        run: |
          pvs-studio-analyzer analyze -f build/compile_commands.json -j
